config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resources :flights, only: [ :index ]
  resources :bookings, only: [ :create, :new, :index, :show ]
  resources :passagers, only: [ :new, :create, :index, :show ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departure_flights, foreign_key: :departure_airport_id, class_name: "Flight"
  has_many :arrival_flights, foreign_key: :arrival_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :passager
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  has_many :bookings
  has_many :passagers, through: :bookings
end

app/models/passager.rb
class Passager < ApplicationRecord
  has_many :bookings
  has_many :flights, through: :bookings

  validates :email, presence: :true, uniqueness: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings=Booking.all
  end

  def new
    @flight=Flight.find_by(id: params[:flight_id])
    @passager=Passager.new
  end

  def create
    @flight=Flight.find_by(id: params[:passager][:flight_id])

    if @flight.nil?
      flash[:no_flight]="The flight has not been found!"
      redirect_to flights_path and return
    end

    # if the email exists in the database we cannot create another booking for the same email
    @passager=Passager.find_or_initialize_by(email: params[:passager][:email]) do |passager|
      passager.name=params[:passager][:name]
    end

    if @passager.save
      flash[:saved_passager]="Passager created succesfully!"
      PassagerMailer.with(passager: @passager).welcome_mail.deliver_now
      @booking=Booking.new(flight_id: @flight.id, passager_id: @passager.id)

      if @booking.save
        flash[:saved_booking]="Booking succesfully saved!"
        redirect_to booking_path(@booking.id)
      else
        flash[:unsaved_booking]="Please add a Booking!"
        render :new
      end

    else
      flash[:create_passager]="Please create a passager!"
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @flights = Flight.all

    @departure_airport = Airport.find_by(id: params[:current_location])
    @arrival_airport = Airport.find_by(id: params[:desired_location])
    flight_date = Flight.find_by(date: params[:flight_date])&.date

    if @departure_airport == @arrival_airport
      flash.now[:same_location] = "You can't fly to the same city!"
      return
    end

    @found_flights = Flight.where(
      date: flight_date,
      arrival_airport_id: @arrival_airport&.id,
      departure_airport_id: @departure_airport&.id
    )

    if @found_flights.empty?
      flash.now[:error] = "No flights found!"
    end
  end
end

app/controllers/passagers_controller.rb
class PassagersController < ApplicationController
  def index
    @passagers=Passager.all
  end

  def new
    @passager = Passager.new
  end

  def create
    @passager=Passager.new(passager_params)

    respond_to do |format|
      if @passager.save
        PassagerMailer.with(passager: @passager).welcome_mail.deliver_now
        flash.now[:successful_creation]="Welcome,#{@passager.name}!"
        format.html { redirect_to @passager }
      else
        flash.now[:creation_error]="Couldn't create the user. Try again!"
        format.html { render :new }
      end
    end
  end

  def show
    @passager = Passager.find(params[:id])
  end

  private

  def passager_params
    params.require(:passager).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passagers_helper.rb
module PassagersHelper
end

app/views/bookings/_flight_details.html.erb
<div class="flight_details_box">
    <% if @flight.present? %>
        <div class="greeting_message">
            <h1>Welcome! Enter your name and email in order to book the following flight:</h1>
        </div>

        <div class="departure_airport">Departure Airport: <%= @flight.departure_airport.name %></div>
        <div class="arrival_airport">Arrival Airport: <%= @flight.arrival_airport.name %></div>
        <div class="flight_date">Flight Date: <%= @flight.date %></div>
        <div class="flight_duration">Flight Duration: <%= @flight.flight_duration %> minutes</div>
    <% end %>
</div>

app/views/bookings/_passager_details.html.erb
<%= stylesheet_link_tag "booking_interface" %>
<div class="container">

    <%# passager details %>
    <div class="passager_details">
        <div class="passager_name">Name: <%= @booking.passager.name %></div>
        <div class="passager_email">Email: <%= @booking.passager.email %></div>
    </div>

    <div class="flight_title">Booked Flight:</div>
    
    <%# flight details %>
    <div class="flight_details">
        
        <div class="departure_airport">Departure Airport: <%= @booking.flight.departure_airport.name %></div>
        <div class="arrival_airport">Arrival Airport: <%= @booking.flight.arrival_airport.name %></div>
        <div class="flight_date">Flight Date: <%= @booking.flight.date %></div>
        <div class="flight_duration">Flight Duration: <%= @booking.flight.flight_duration %> minutes</div>
    </div>


    <div class="go_back">
        <button><%= link_to "Back to Flights",  flights_path, class:"edit_button" %></button>
    </div>
</div>

app/views/bookings/index.html.erb
<% @bookings.each do |bkn| %>
    <%= bkn.passager_id %>
<% end %>

app/views/bookings/new.html.erb
<div class="container">
  <%= render "flight_details" , flight:@flight %>
  <%= form_with model: @passager, url: bookings_path, method: :post, data: { turbo: false } do |f| %>
    <!-- Hidden field to include the flight ID -->
    <%= f.hidden_field :flight_id, value: @flight.id %>

    <div>
      <%= f.label :name, "Passenger Name" %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :email, "Passenger Email" %>
      <%= f.email_field :email %>
    </div>

    <%= f.submit "Create Booking" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<%= render "passager_details"%>

app/views/flights/_search_form.html.erb
<div class="search_content">
<%=form_with url: flights_path,method: :get do |form|%>
    <div class="search_box">
        <div class="original_location">
            <%=form.label :current_location%>  
            <%=form.collection_select :current_location,@airports,:id,:name%>              
        </div>

        <div class="desired_location">
            <%=form.label :desired_location%>
            <%=form.collection_select :desired_location,@airports.all,:id,:name%>
        </div>

        <div class="flight_dates">
            <%=form.label :flight_date%>
            <%=form.select :flight_date, options_for_select(@flights.distinct.pluck(:date))%>
        </div>

        <div class="nr_passagers">
            <%=form.label :passagers%>
            <%= form.number_field :passagers, max: 4, min: 1 ,value:1%>
        </div>

        <%=form.submit "Search Flights"%>
    </div>
<%end%>
</div>

app/views/flights/_search_results.html.erb
<%= stylesheet_link_tag "flight_results" %>
<div class="content">
<%= form_with url: new_booking_path, method: :get, data: { turbo: false } do |f| %>
  <div class="results_box">
    <% if @found_flights.present? %>
      <% @found_flights.each do |flightss| %>
        <div class="each_flight">
          <div class="radio_button"><%= f.radio_button :radio_btn,flightss.id %></div>
          <div class="departure_airport_name"><%= flightss.departure_airport.name %></div>
          <div class="arrival_airport_name"><%= flightss.arrival_airport.name %></div>
          <div class="flight_date"><%= flightss.date %></div>
          <div class="flight_passagers"><%= flightss.flight_duration %></div>
          <%= f.hidden_field :flight_id, value: flightss.id %>
        </div>
      <% end %> 
    <div class="book_flight"><%= f.submit "Book Flight" %></div>
      
    <% else %>
      <% if flash[:same_location] %>
          <div class="same_location_warning"><%= flash[:same_location] %></div>
        <% elsif flash[:error] %>
          <div class="no_flight_warning"><%= flash[:error] %></div>
        <% end %>
    <% end %>
  </div>
<% end %>
</div>

app/views/flights/index.html.erb
<div class="nice_container">
    <%= render "search_form" %>  
    <%= render "search_results" %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passagers/index.html.erb
<% @passagers.each do |psg| %>
    <%= psg.name %>
    <%= psg.email %>

<% end %>

app/views/passagers/show.html.erb
<div class="name">Name: <%= @passager.name %></div>
<div class="email">Email: z<%= @passager.email %></div>